SELECT B.FOOD_TYPE
     , B.REST_ID
     , B.REST_NAME
     , B.FAVORITES
 FROM REST_INFO B
    , (
        SELECT A.FOOD_TYPE      AS FOOD_TYPE
             , MAX(A.FAVORITES) AS MAX_FAVORITES
          FROM REST_INFO A
         WHERE 1=1
        GROUP BY FOOD_TYPE  
      ) A
WHERE 1=1
  AND B.FOOD_TYPE = A.FOOD_TYPE
  AND B.FAVORITES = A.MAX_FAVORITES
GROUP BY B.FOOD_TYPE      
     , B.REST_ID
     , B.REST_NAME
     , B.FAVORITES
 ORDER BY B.FOOD_TYPE DESC


