SELECT TO_CHAR(B.SALES_DATE,'YYYY')             AS YEAR
     , TO_NUMBER(TO_CHAR(B.SALES_DATE,'MM'  ))  AS MONTH
     , COUNT(DISTINCT A.USER_ID) AS PUCHASED_USERS
     , ROUND(COUNT(DISTINCT A.USER_ID) / 
             (SELECT COUNT(*) FROM USER_INFO 
                             WHERE 1=1
                               AND TO_CHAR(A.JOINED,'YYYY') = '2021' ) , 1
            ) AS PUCHASED_RATIO
     
 FROM ( SELECT A.* 
      FROM USER_INFO A
    WHERE 1=1
      AND TO_CHAR(A.JOINED,'YYYY') = '2021'
      ) A
    , ONLINE_SALE B    
WHERE 1=1
  AND A.USER_ID = B.USER_ID
GROUP BY TO_CHAR(B.SALES_DATE,'YYYY') 
       , TO_CHAR(B.SALES_DATE,'MM'  )
ORDER BY 2
       , 1