-- 코드를 입력하세요
SELECT A.CAR_ID
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
    , CAR_RENTAL_COMPANY_CAR B
WHERE 1=1
  AND A.CAR_ID = B.CAR_ID (+)
  AND TO_CHAR(A.START_DATE,'YYYYMM') = '202210' 
  AND B.CAR_TYPE = '세단'
 GROUP BY A.CAR_ID
ORDER BY A.CAR_ID DESC